name: MinigameByAI
version: '1.0.0-SNAPSHOT'
main: dev.ethans.relicrush.RelicRushPlugin
api-version: '1.21'

commands:
  relicreload:
    description: Reload the plugin
    usage: /minigamereload
    permission: relicrush.reload

  relicspawn:
    description: Set location as a relic spawn
    usage: /spawnrelic <common|rare|golden>
    permission: relicrush.relicspawn

  relicdeposit:
    description: Mark a location as a relic deposit
    usage: /relicdeposit <team>
    permission: relicrush.relicdeposit